#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#zstyle ':prezto:module:editor' dot-expansion 'yes'
#zstyle ':prezto:module:terminal' auto-title 'yes'

unsetopt AUTO_CD

export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11R6/bin:/Users/james/bin

if [ -d /Users/james/pebble ]; then
    export PATH=$PATH:/Users/james/pebble/PebbleSDK-2.0.0/bin
fi

if [ -d /Users/james/bin ]; then
    export PATH=$PATH:/Users/james/bin
fi

if [ $( hostname -s ) = "yukino" ]; then
    # At work
    hash -d puppet=/Users/jseward/src/puppet
    hash -d sm5=/Users/jseward/src/sm5
fi

export COPYFILE_DISABLE=true

if [ -f /usr/local/bin/aws_zsh_completer.sh ]; then
    source /usr/local/bin/aws_zsh_completer.sh
fi

alias flake8="flake8 --ignore=E501"
alias md5sum=md5
alias vim=nvim
alias rr=rake rspec

setopt TRANSIENT_RPROMPT
REPORTTIME=10

function fuck() {
    killall -9 $2;
    if [ $? == 0 ]
        then
        echo
        echo " (╯°□°）╯︵$(echo $2|flip &2>/dev/null)"
        echo
    fi
}

export EDITOR=nvim
PERL_MB_OPT="--install_base \"/Users/jseward/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/jseward/perl5"; export PERL_MM_OPT;


function tidy_nagios() {
    python ~/src/puppet/modules/nagios/tidy_nagios.py "$1" > "${1}_tmp" && mv "$1_tmp" "$1"
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

function watch_elb () {
	watch -n 10 "aws elb describe-instance-health --load-balancer-name "$1" | jq '.InstanceStates[].State' | sort | uniq -c"
}

function agvim () {
	CHOICE=$(ag --color $* | fzf -0 -1 --ansi)
	if [ ! -z "$CHOICE" ]; then
		# Open vim at the selected file and line, but also run the Ag scan
		# the ! on Ag! stops Ag jumping to the first match, and the wincmd gives the editor window focus
		nvim $( echo "$CHOICE" | awk 'BEGIN { FS=":" } { printf "+%d %s\n", $2, $1 } ') +"Ag! '$*'" "+wincmd k"
	fi
}

function try_ssh () {
	SUCCESS=0
	while [ $SUCCESS -eq 0 ]; do
		ssh -o "ConnectTimeout 30" $*
		RESULT=$?
		if [ $RESULT -ne 255 ]; then
			SUCCESS=1
		else
			echo "--> SSH return code was $RESULT"
			print "Waiting to retry ssh..."
			sleep 10
			echo "--> Retrying..."
		fi
	done
}

zstyle ':prezto:module:editor:info:keymap:primary' format ' %B%F{2}❯%f%b'

export FZF_DEFAULT_OPTS='-e'

function vpn () {
	if $( pgrep vpnc > /dev/null ); then
		echo "--> Disconnecting VPN"
		sudo /usr/local/sbin/vpnc-disconnect
	else
		echo "--> Connecting VPN"
		sudo /usr/local/sbin/vpnc
	fi
}

function test-module {
	../../ci/docker.sh 1 "$( basename $PWD )"
}
